(1) Use the file **bank.csv** to explore the dataset. Observe the features: Are they numbers? Are they strings? Are they binary? Are they continuous?

In [6]:
import pandas as pd

cols = ['age','job','marital','education','default','balance','housing','loan','contact','day','month','duration','campaign','pdays','previous','poutcome','y']

data = pd.read_csv('C:/Users/cat/DAT_SF_14/homework/hw3/bank.csv', header = True, names = cols, sep =";")

data.groupby(['marital']).marital.count()

marital
divorced     528
married     2796
single      1196
Name: marital, dtype: int64

In [7]:
data.groupby(['education']).education.count()

education
primary       677
secondary    2306
tertiary     1350
unknown       187
Name: education, dtype: int64

In [8]:
data.groupby(['housing']).housing.count()

housing
no         1961
yes        2559
Name: housing, dtype: int64

(2) Learn about label encoders at the following link and use what you learn to transform the features to numerical features: http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html

In [9]:
import numpy as np
from sklearn import preprocessing
lab = preprocessing.LabelEncoder()
data.job = lab.fit_transform(data.job)
data.marital = lab.fit_transform(data.marital)
data.education = lab.fit_transform(data.education)
data.default = lab.fit_transform(data.default)
data.balance = lab.fit_transform(data.balance)
data.housing = lab.fit_transform(data.housing)
data.loan = lab.fit_transform(data.loan)
data.contact = lab.fit_transform(data.contact)
data.month = lab.fit_transform(data.month)
data.poutcome = lab.fit_transform(data.poutcome)
data.y = lab.fit_transform(data.y)

data

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,33,7,1,1,0,2030,1,1,0,11,8,220,1,339,4,0,0
1,35,4,2,2,0,1303,1,0,0,16,0,185,1,330,1,0,0
2,30,4,1,2,0,1352,1,1,2,3,6,199,4,-1,0,3,0
3,59,1,1,1,0,274,1,0,2,5,8,226,1,-1,0,3,0
4,35,4,2,2,0,934,0,0,0,23,3,141,2,176,3,0,0
5,36,6,1,2,0,569,1,0,0,14,8,341,1,330,2,1,0
6,39,9,1,1,0,420,1,0,0,6,8,151,2,-1,0,3,0
7,41,2,1,2,0,491,1,0,2,14,8,57,2,-1,0,3,0
8,43,7,1,0,0,218,1,1,0,17,0,313,1,147,2,0,0
9,39,7,1,1,0,2254,1,0,2,20,8,273,1,-1,0,3,0
10,43,0,1,1,0,531,1,0,0,17,0,113,2,-1,0,3,0
11,36,9,1,2,0,1173,0,0,0,13,1,328,2,-1,0,3,0
12,20,8,2,1,0,750,0,0,0,30,0,261,1,-1,0,3,1
13,31,1,1,1,0,620,1,1,0,29,4,89,1,241,1,0,0
14,40,4,1,2,0,464,0,1,0,29,1,189,2,-1,0,3,0
15,56,9,1,1,0,1949,0,0,0,27,1,239,5,-1,0,3,0
16,37,0,2,2,0,1629,1,0,0,20,0,114,1,152,2,0,0
17,25,1,2,0,0,163,1,0,2,23,8,250,1,-1,0,3,0
18,31,7,1,1,0,405,0,0,0,7,5,148,1,152,1,1,0
19,38,4,0,3,0,274,1,0,0,18,9,96,2,-1,0,3,0
20,42,4,0,2,0,290,0,0,0,19,9,140,3,-1,0,3,0
21,44,7,2,1,0,380,0,0,2,12,6,109,2,-1,0,3,0
22,44,2,1,1,0,367,0,0,0,7,5,125,2,-1,0,3,0
23,26,3,1,2,0,778,0,0,0,30,4,169,3,-1,0,3,0
24,41,4,1,2,0,2117,0,0,0,20,9,182,2,-1,0,3,0
25,55,1,1,0,0,845,1,0,2,5,8,247,1,-1,0,3,0
26,67,5,1,3,0,900,0,0,1,17,1,119,1,105,2,0,0
27,56,6,1,1,0,966,0,1,0,30,5,149,2,-1,0,3,0
28,53,0,1,1,0,379,0,1,0,21,1,74,2,-1,0,3,0
29,68,5,0,1,0,1965,0,0,1,14,5,897,2,-1,0,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4490,35,1,2,1,0,274,1,0,0,16,0,169,1,-1,0,3,0
4491,32,9,2,1,0,571,1,1,0,16,0,346,1,234,3,0,0
4492,28,9,2,2,0,274,1,0,2,4,6,205,6,-1,0,3,0
4493,26,9,2,1,0,880,1,0,2,28,8,576,3,-1,0,3,1
4494,48,4,1,2,0,1217,1,0,1,18,9,1476,3,-1,0,3,0
4495,30,1,2,1,0,623,0,0,0,28,5,171,3,-1,0,3,0
4496,31,2,2,2,0,312,0,0,0,20,9,185,2,-1,0,3,0
4497,31,4,1,2,0,1221,1,0,2,27,8,676,6,-1,0,3,0
4498,45,1,0,0,0,1070,0,0,0,21,9,362,1,-1,0,3,0
4499,38,0,1,1,0,1967,1,0,0,12,8,193,2,-1,0,3,0
4500,34,4,1,2,0,560,1,0,0,26,1,63,4,-1,0,3,0
4501,42,7,1,1,0,216,1,1,0,5,3,43,1,-1,0,3,0
4502,60,6,1,0,0,622,0,1,0,29,5,816,6,-1,0,3,1
4503,42,1,2,1,0,1162,1,1,0,13,8,951,3,370,4,0,1
4504,32,0,2,1,0,838,1,0,2,26,8,1234,3,-1,0,3,1
4505,42,10,0,2,0,183,0,0,0,29,1,85,4,-1,0,3,0
4506,33,7,1,1,0,551,1,0,0,17,0,306,1,-1,0,3,0
4507,42,0,1,3,0,859,1,1,2,16,8,509,2,-1,0,3,0
4508,51,9,1,2,0,1670,0,0,0,30,9,210,3,-1,0,3,0
4509,36,9,0,1,0,796,1,0,2,20,8,129,2,-1,0,3,0
4510,46,1,1,1,0,880,1,0,2,15,8,1263,2,-1,0,3,1
4511,40,1,1,1,0,1170,1,0,2,29,8,660,2,-1,0,3,0
4512,49,1,1,1,0,584,0,0,0,14,1,356,2,-1,0,3,0
4513,38,1,1,1,0,1232,1,0,0,20,0,45,4,153,1,0,0
4514,32,7,2,1,0,723,1,0,0,7,5,624,5,-1,0,3,0
4515,33,7,1,1,0,119,1,0,0,30,5,329,5,-1,0,3,0
4516,57,6,1,2,1,0,1,1,2,9,8,153,1,-1,0,3,0
4517,57,9,1,1,0,558,0,0,0,19,1,151,11,-1,0,3,0
4518,28,1,1,1,0,1187,0,0,0,6,3,129,4,211,3,1,0
4519,44,2,2,2,0,1186,1,1,0,3,0,345,2,249,7,1,0

(3) Build a decision tree model to predict whether a prospect will buy the product.

In [10]:
#Defining my columns for splitting my data
cols = data.columns[0:-1]

X = data[cols]
y = data.y

from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [11]:
print X_train
print y_train
print X_test
print y_test

[[ 49   4   1 ...,  -1   0   3]
 [ 54   9   1 ...,  -1   0   3]
 [ 42   1   2 ...,  -1   0   3]
 ...,
 [ 31   1   1 ..., 322   1   1]
 [ 43   1   2 ..., 363   1   0]
 [ 33   1   1 ..., 308   2   1]]
[0 0 0 ..., 0 0 0]
[[ 32   1   1 ...,  -1   0   3]
 [ 35   4   1 ...,  88   1   1]
 [ 55   6   1 ..., 174  12   1]
 ...,
 [ 36   1   1 ...,  -1   0   3]
 [ 35   4   1 ...,  -1   0   3]
 [ 40   1   1 ...,  -1   0   3]]
[0 0 0 ..., 0 0 0]

In [12]:
from sklearn.tree import DecisionTreeClassifier
treeclass = DecisionTreeClassifier(random_state=1)
treeclass.fit(X_train, y_train)

DecisionTreeClassifier(compute_importances=None, criterion='gini',
            max_depth=None, max_features=None, max_leaf_nodes=None,
            min_density=None, min_samples_leaf=1, min_samples_split=2,
            random_state=1, splitter='best')

In [13]:
preds = treeclass.predict(X_test)
for i in preds:
    print i

0
0
0
0
0
0
1
0
0
0
0
1
0
0
0
0
0
0
1
0
0
1
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
0
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
1
1
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
1
0
0
0
1
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
1
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
1
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
1
0
0
0
0
1
1
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
1
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
1
1
0
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
1
1
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
1
0
0
0
0
0
1
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
1
0
0
1
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
1
0
0
1
0
0
0
0
1
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
1
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
1
0
0
0
1
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
1
1
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
1
0
1
1
0
0
0
1
0
0
0
0
0
0
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
1
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
1
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0

(4) Evaluate the accuracy of your decision tree model using cross validation.

In [14]:
#importing cross-validation
from sklearn.cross_validation import cross_val_score

clf = DecisionTreeClassifier(random_state=0)
scores = cross_val_score(clf, X_test, y_test, cv=4)
print scores

[ 0.8409894   0.80565371  0.83038869  0.79715302]

In [15]:
float(sum(preds == y_test))/ len(y_test)

0.8460176991150442

(5) Repeat the analysis and cross validation with the file **bank-additional-full.csv**. How does the performance of the model change (with the additional training examples and additional features)?

In [16]:
cols_full = ['age','job','marital','education','default','housing','loan',
             'contact','month','day_of_week','duration','campaign','pdays',
             'previous','poutcome','emp_var_rate','cons_price_idx','cons_conf_idx',
             'euribor3m','nr_employed','y']

data_full = pd.read_csv('C:/Users/cat/DAT_SF_14/homework/hw3/bank-additional-full.csv', header = True, names = cols_full, sep =";")

data_full.job = lab.fit_transform(data_full.job)
data_full.marital = lab.fit_transform(data_full.marital)
data_full.education = lab.fit_transform(data_full.education)
data_full.default = lab.fit_transform(data_full.default)
data_full.housing = lab.fit_transform(data_full.housing)
data_full.loan = lab.fit_transform(data_full.loan)
data_full.contact = lab.fit_transform(data_full.contact)
data_full.month = lab.fit_transform(data_full.month)
data_full.day_of_week = lab.fit_transform(data_full.day_of_week)
data_full.duration = lab.fit_transform(data_full.duration)
data_full.campaign = lab.fit_transform(data_full.campaign)
data_full.pdays = lab.fit_transform(data_full.pdays)
data_full.previous = lab.fit_transform(data_full.previous)
data_full.poutcome = lab.fit_transform(data_full.poutcome)
data_full.emp_var_rate = lab.fit_transform(data_full.emp_var_rate)
data_full.cons_price_idx = lab.fit_transform(data_full.cons_price_idx)
data_full.cons_conf_idx = lab.fit_transform(data_full.cons_conf_idx)
data_full.euribor3m = lab.fit_transform(data_full.euribor3m)
data_full.nr_employed = lab.fit_transform(data_full.nr_employed)
data_full.y = lab.fit_transform(data_full.y)

cols_full = data_full.columns[0:-1]

X_full = data_full[cols_full]
y_full = data_full.y

from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_full, y_full, random_state=1)

clf = DecisionTreeClassifier(random_state=0)
scores = cross_val_score(clf, X_test, y_test, cv=4)
print scores

[ 0.85708738  0.87805825  0.88150738  0.89623008]

In [18]:
treeclass = DecisionTreeClassifier(random_state=1)
treeclass.fit(X_train, y_train)
preds = treeclass.predict(X_test)

float(sum(preds == y_test))/ len(y_test)

0.8894823735068467

Model provides greater accuracy with the additional training examples and features